project:
  type: book
  pre-render: R/helper.R

book:
  title: "Reporters Without Borders (RWB)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon_io/apple-touch-icon.png"
  site-url: https://bookdown.org/pbaumgartner/rwb-book/
  repo-url: https://github.com/petzi53/rwb-book
  repo-branch: master
  repo-actions: [edit, issue, source]
  page-navigation: true

  chapters:
    - index.qmd
    - part: "Preliminaries"
      chapters:
        - 011-get-rwb-data.qmd
        - 041-map-with-tmap.qmd
    - part: "Explore Leaflet"
      chapters:
        - 051-leaflet-basics.qmd
        - 052-leaflet-choropleth.qmd
        - 053-leaflet-advanced.qmd
    - part: "RWB Dashboard"
      chapters:
        - 061-functionality.qmd
        - 071-ui-design.qmd
        - 081-line-chart.qmd
        - 091-bump-chart-1.qmd
        - 092-bump-chart-2.qmd
        - 093-bump-chart-3.qmd
        - 101-new-navigation.qmd

bibliography:
    - references.bib
reference-section-title: References
# citeproc: true


format:
  html:
    theme: cosmo
    css:
     - quarto.css
     - glossary.css
    number-sections: true
    toc-depth: 6
    toc-expand: true
    toc_float: true
    code-fold: show
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

filters:
   - include-code-files
   - section-bibliographies
   - shinylive
   - base64

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto

lightbox: true



crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  custom:
    - kind: float
      reference-prefix: Important
      key: imp
    - kind: float
      reference-prefix: Commitment
      key: com
    - kind: float
      reference-prefix: Report
      key: rep
    - kind: float
      reference-prefix: Resource
      key: res
    - kind: float
      reference-prefix: Package Profile
      key: pak
    - kind: float
      reference-prefix: Bullet List
      key: bul
    - kind: float
      reference-prefix: Numerical List
      key: num
    - kind: float
      reference-prefix: Note
      key: not
    - kind: float
      reference-prefix: Explanation
      key: exp
    - kind: float
      reference-prefix: Tip
      key: tip
    - kind: float
      reference-prefix: Checklist
      key: tdo
    - kind: float
      reference-prefix: Collection Code
      key: col
    - kind: float
      reference-prefix: Watch-out
      key: wat



tip-cap-location: top
pak-cap-location: top
bul-cap-location: bottom

language:
   crossref-cnj-title: "R Code"             # replaces "Conjecture"
   crossref-cor-title: "Assessment"         # replaces "Corollary"
   crossref-def-title: "Experiment"         # replaces "Definition"
   crossref-exm-title: "Code Collection"    # replaces  "Example"
   crossref-exr-title: "Exercise"           # remains  "Exercise"
   crossref-fig-title: "Graph"              # replaces "Figure"
   crossref-lem-title: "Resource"           # replaces "Lemma"
   crossref-lst-title: "Listing / Output"   # replaces  "Listing"
   crossref-prp-title: "Procedure"          # replaces "Proposition"
   crossref-tbl-title: "Table"              # remains  "Table"
   crossref-thm-title: "Formula"            # replaces "Theorem"
#   crossref-int-title: "Interpretation"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Hint"             # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Watch out!"   # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "ToDo"         # yellow
